sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: zhuyonghao.xyz
    port: 3306
    database: sky_take_out
    username: sky_take_out
    password: fxX4TkfXMzKWy4Ek
